root -l -b -q utils/rooutil/examples/PrintEvents.C++\(\"nts.ntuple.mock.root\",true\)
root -l -b -q utils/rooutil/examples/PrintEvents.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\",true\)
root -l -b -q utils/rooutil/examples/PlotEntranceMomentum.C++\(\"nts.ntuple.mock.root\"\)
root -l -b -q utils/rooutil/examples/CreateTree.C++\(\"nts.ntuple.mock.root\"\)
root -l -b -q utils/rooutil/examples/TimingTest.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\"\)
root -l -b -q utils/rooutil/examples/PlotEntranceMomentumResolution.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\"\)
root -l -b -q utils/rooutil/examples/PlotTrkCaloHitEnergy.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\"\)
root -l -b -q utils/rooutil/examples/PlotCRVPEs.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\"\)
root -l -b -q utils/rooutil/examples/PlotEntranceMomentumCRVCut.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\"\)

root -l -b -q utils/rooutil/examples/PrintEvents.C++\(\"nts.ntuple.mockNoMC.root\",false\)
root -l -b -q utils/rooutil/examples/PlotEntranceMomentum.C++\(\"nts.ntuple.mockNoMC.root\"\)
root -l -b -q utils/rooutil/examples/CreateTree.C++\(\"nts.ntuple.mockNoMC.root\"\)
root -l -b -q utils/rooutil/examples/TimingTest.C++\(\"nts.ntuple.mockNoMC.root\"\)

root -l -b -q validation/create_val_file_rooutil.C++\(\"../data/nts.mu2e.MDS1f.MDC2020ai_perfect_v1_3.root\",\"val.ntuple.rooutil.root\"\)
